ARCH=Windows
ARCH_PATHS:=

CC:=i686-mingw32-gcc -Isrc -DWIN32
STRIP:=i686-mingw32-strip
NEKO_FLAGS:=-shared -L/usr/lib -lneko -lws2_32 -lssl32 -leay32
LOCAL_FLAGS:=-I../include -Iinclude -Isrc/windows

include Makefile.common
