dlls:
	cd dll_src && make -f Makefile.linux

clean:
	$(RM) ext/haxelib.xml
	$(RM) *.n

clean-kate:
	find . -name "*~" -exec rm {} \;

clean-neko:
	find . -name "*.n" -exec rm {} \;

distclean: clean clean-kate clean-neko