ARCH=Linux
PROJECT:=sys_posix
NDLL:=ndll/Linux/$(PROJECT).ndll
ARCH_PATHS:=

CC:=i686-pc-linux-gnu-gcc -Isrc -D _GNU_SOURCE
NEKO_FLAGS:=-fPIC -shared -L/usr/lib -L$(HOME)/neko -lneko -lz -ldl
LOCAL_FLAGS:=$(CFLAGS) -I../include -Iinclude -Isrc/linux -DLINUX
STRIP:=strip

include Makefile.common
