ifeq ($(ARCH),linux)
  override BUILD=BUILD_LINUX
  override ARCH=linux
  override ARCH_CAP=Linux
  override CC=i686-pc-linux-gnu-gcc
  override EXE=
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif
ifeq ($(ARCH),linux64)
  override BUILD=BUILD_LINUX
  override ARCH=linux64
  override ARCH_CAP=Linux64
  override CC=x86_64-pc-linux-gnu-gcc
  override EXE=
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif
ifeq ($(ARCH),windows)
  override BUILD=BUILD_WINDOWS
  override ARCH=windows
  override ARCH_CAP=Windows
  override CC=i686-mingw32-gcc
  override EXE=.exe
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif
ifeq ($(ARCH),mac)
  override BUILD=BUILD_MAC
  override ARCH=mac
  override ARCH_CAP=Mac
  override CC=gcc
  override EXE=
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif
ifeq ($(ARCH),bsd)
  override BUILD=BUILD_BSD
  override ARCH=bsd
  override ARCH_CAP=BSD
  override CC=gcc
  override EXE=
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko -L/usr/local/lib
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif

# What follows are cross compiler targets

ifeq ($(ARCH),wine)
  override BUILD=BUILD_WINDOWS
  override ARCH=windows
  override ARCH_CAP=Windows
  override CC=i686-mingw32-gcc
  override EXE=.exe
  override NEKO=wine neko
  override NEKOTOOLS=wine nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif
ifeq ($(ARCH),xbsd)
  override BUILD=BUILD_WINDOWS
  override ARCH:=bsd
  override ARCH=bsd
  override ARCH_CAP=Bsd
  override CC=i686-freebsd-gcc
  override EXE=
  override NEKO=neko
  override NEKOTOOLS=nekotools
  override LIBPATH=-L/usr/lib -L$(HOME)/neko
  override INCPATH=-I ./ -I ../include -I /usr/include/neko
  override LIBS=-lneko
endif

