PROJECT:=ncrypt
NDLL:=../../ext/ndll/Linux64/$(PROJECT).ndll
ARCH_PATHS:=

CC:=gcc -Isrc
NEKO_FLAGS:=-fPIC -shared -L/usr/lib -lneko -lz -ldl
LOCAL_FLAGS:=-Iinclude -Isrc/linux -DLINUX
STRIP:=strip

include Makefile.common
