ARCH=Linux
ARCH_PATHS:=

CC:=i686-pc-linux-gnu-gcc -Isrc
NEKO_FLAGS:=-fPIC -shared -L/usr/lib -L$(HOME)/neko -lneko -lz -ldl
LOCAL_FLAGS:=-I../include -Iinclude -Isrc/linux -DLINUX
STRIP:=strip

include Makefile.common
