#	swfmill simple tan.xml hxwidgets_tan.swf
# HxwSkinAssetsTan

COMPC:=compc
MXMLC:=mxmlc
SKINS=tan

all: $(SKINS)

tan: dummy
	neko ../../as3libtool.n -i tan -o tan_out -f hxwidgets_skin_tan.swf --capitalize

clean:
	rm -rf tan_out

dummy:


