#	swfmill simple tan.xml hxwidgets_tan.swf
# HxwSkinAssetsTan

COMPC:=compc
MXMLC:=mxmlc

all: tan

tan: dummy
	neko ../../as3libtool.n -i skins/Tan -o hxwidgets_tan.swf --build out --img-append _tan

clean:
	rm -f hxwidgets_tan.swf
	rm -rf out

dummy:


