all: crypt reliableudp

crypt: dummy
	cd crypt && make -f Makefile.linux

reliableudp: dummy
	cd reliableudp && make -f Makefile.linux

fileext: dummy
	cd fileext && make clean && make ARCH=linux && make ARCH=linux install

dummy:
