PROJECT:=xdiff
NDLL:=ndll/Linux/$(PROJECT).ndll
ARCH_PATHS:=

CC:=gcc -Isrc
NEKO_FLAGS:=-fPIC -shared -L/usr/lib $(LDFLAGS) -L$(HOME)/neko -lneko -lxdiff -ldl
LOCAL_FLAGS:=$(CFLAGS) -I../include -Iinclude -Isrc/linux -DLINUX
STRIP:=strip

include Makefile.common
